### ISSUE TITLE
build error when ninja searches for `libamdhip.so.XXX-` with trailing dash

### ISSUE THREAD

**Issue by izypd** [rocm-arch/python-pytorch-rocm#8]
Hello! I am using `yay -S rocm-dev rocm-utils rocm-libs rccl` then `yay -S python-pytorch-opt-rocm` to build pytorch in EndeavourOS. First command succeeded, next command failed! I am using arch4edu. I had installed a new EndeavourOS and run the command above again but got same error.
Error code as so:
```
[4490/4849] Linking CXX shared library lib/libtorch_hip.so
FAILED: lib/libtorch_hip.so
: && /usr/bin/c++ -fPIC -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG  -Wl,--no-as-needed -rdynamic -shared -Wl,-soname,libtorch_hip.so -o lib/libtorch_hip.so caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHReduceApplyUtils.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/
```
code is too long, so I skip some.
```
CMakeFiles/torch_hip.dir/__/torch/csrc/jit/tensorexpr/cuda_codegen.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/torch/csrc/cuda/nccl.cpp.o  -Wl,-rpath,/home/ym/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.0rc1-rocm/build/lib:/opt/rocm/hip/lib:/opt/rocm/miopen/lib:/opt/rocm/rccl/lib:/opt/rocm/roctracer/lib:/opt/rocm/rocblas/lib:/opt/rocm/rocfft/lib:/opt/rocm/hiprand/lib:/opt/rocm/hipsparse/lib:/opt/intel/mkl/lib/intel64:/opt/rocm/lib:/opt/rocm/rocrand/lib:/usr/lib/openmpi:  lib/libc10_hip.so  /opt/rocm/hip/lib/libamdhip64.so  /opt/rocm/miopen/lib/libMIOpen.so  /opt/rocm/rccl/lib/librccl.so  /opt/rocm/hip/lib/libamdhip64.so  /opt/rocm/roctracer/lib/libroctx64.so  /opt/rocm/rocblas/lib/librocblas.so.0.1  /opt/rocm/rocfft/lib/librocfft.so.0.1  /opt/rocm/hiprand/lib/libhiprand.so.1.1  /opt/rocm/hipsparse/lib/libhipsparse.so.0.1  lib/libgloo_hip.a  lib/libc10.so  -Wl,--no-as-needed,"/home/ym/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.0rc1-rocm/build/lib/libtorch_cpu.so" -Wl,--as-needed  lib/libprotobuf.a  /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so  /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so  /opt/intel/mkl/lib/intel64/libmkl_core.so  -fopenmp  /usr/lib/libpthread.so  -lm  /usr/lib/libdl.so  lib/libdnnl.a  -pthread  -ldl  /opt/rocm/hip/lib/libamdhip64.so.3.8.20413-  -L/opt/rocm/llvm/lib/clang/11.0.0/include/../lib/linux  -lclang_rt.builtins-x86_64  /opt/rocm/hip/lib/libamdhip64.so  lib/libgloo.a  /usr/lib/openmpi/libmpi_cxx.so  /usr/lib/openmpi/libmpi.so  -lpthread  -Wl,-rpath-link,/opt/rocm/lib:/opt/rocm/rocfft/lib:/opt/rocm/rocrand/lib && :
c++: 错误：当输入来自标准输入设备时，需要 -E 或 -x
```
and build stopped after the code below
```
[4501/4849] Building CXX object test_api/CMakeFiles/test_api.dir/modules.cpp.o
cc1plus: 警告：command-line option ‘-Wno-duplicate-decl-specifier’ is valid for C/ObjC but not for C++
cc1plus: 附注：unrecognized command-line option ‘-Wno-implicit-int-float-conversion’ may have been intended to silence earlier diagnostics
cc1plus: 附注：unrecognized command-line option ‘-Wno-unused-command-line-argument’ may have been intended to silence earlier diagnostics
cc1plus: 附注：unrecognized command-line option ‘-Wno-exceptions’ may have been intended to silence earlier diagnostics
cc1plus: 附注：unrecognized command-line option ‘-Wno-inconsistent-missing-override’ may have been intended to silence earlier diagnostics
cc1plus: 附注：unrecognized command-line option ‘-Wno-macro-redefined’ may have been intended to silence earlier diagnostics
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 720, in <module>
    build_deps()
  File "setup.py", line 311, in build_deps
    build_caffe2(version=version,
  File "/home/ym/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.0rc1-rocm/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/ym/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.0rc1-rocm/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/home/ym/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.0rc1-rocm/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '12']' returned non-zero exit status 1.
==> 错误： 在 build() 中发生一个错误。
    正在放弃...
生成时出错: python-pytorch-rocm (python-pytorch-opt-rocm)
```

**Comment by acxz** [comment]
This seems like an upstream issue to me, can you make an issue at the upstream repo: https://github.com/pytorch/pytorch?

**Comment by acxz** [comment]
> c++: 错误：当输入来自标准输入设备时，需要 -E 或 -x

English: `c++: error: -E or -x required when input is from standard input`

**Comment by acxz** [comment]
Here is a quick stackoverflow search on the error: https://stackoverflow.com/questions/26774535/e-or-x-required-when-input-is-from-standard-input

**Comment by izypd** [comment]
> This seems like an upstream issue to me, can you make an issue at the upstream repo: https://github.com/pytorch/pytorch?

I made an issue: pytorch/pytorch#46528

**Comment by acxz** [comment]
[out.txt](https://github.com/rocm-arch/python-pytorch-rocm/files/5433851/out.txt)

**Comment by acxz** [comment]
@izypd I believe this issue has been resolved, with the later versions of this package. Feel free to comment on this if you are still facing this issue.

**Comment by acxz** [comment]
@erratic-c-programmer

```
[4432/4780] Linking CXX shared library lib/libtorch_hip.so
FAILED: lib/libtorch_hip.so
: && /usr/bin/c++ -fPIC -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG  -Wl,--no-as-needed -rdynamic -shared -Wl,-soname,libtorch_hip.so -o lib/libtorch_hip.so caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHReduceApplyUtils.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHBlas.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHSleep.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHStorage.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHStorageCopy.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHTensor.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHTensorCopy.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHTensorMath.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHTensorMathBlas.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHTensorMathMagma.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHTensorMathPairwise.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHTensorMathReduce.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHTensorIndex.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHTensorRandom.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHTensorScatterGather.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHTensorSort.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHSortUtils.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorSortByte.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathPointwiseByte.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathReduceByte.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMaskedByte.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorTopKByte.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorSortChar.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathPointwiseChar.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathReduceChar.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMaskedChar.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorTopKChar.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorSortShort.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathPointwiseShort.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathReduceShort.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMaskedShort.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorTopKShort.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorSortInt.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathPointwiseInt.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathReduceInt.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMaskedInt.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorTopKInt.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorSortLong.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathPointwiseLong.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathReduceLong.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMaskedLong.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorTopKLong.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorSortHalf.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathPointwiseHalf.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathReduceHalf.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMaskedHalf.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorTopKHalf.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorSortFloat.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathPointwiseFloat.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathReduceFloat.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMaskedFloat.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorTopKFloat.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorSortDouble.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathPointwiseDouble.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathReduceDouble.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMaskedDouble.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorTopKDouble.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathPointwiseBool.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathReduceBool.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMaskedBool.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMathReduceBFloat16.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMaskedBFloat16.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorSortBFloat16.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorTopKBFloat16.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THHUNN/torch_hip_generated_ClassNLLCriterion.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THHUNN/torch_hip_generated_GatedLinearUnit.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THHUNN/torch_hip_generated_LogSigmoid.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THHUNN/torch_hip_generated_MultiLabelMarginCriterion.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THHUNN/torch_hip_generated_MultiMarginCriterion.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THHUNN/torch_hip_generated_RReLU.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THHUNN/torch_hip_generated_SpatialClassNLLCriterion.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THHUNN/torch_hip_generated_SpatialConvolutionMM.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THHUNN/torch_hip_generated_SpatialDepthwiseConvolution.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/hip/detail/torch_hip_generated_IndexUtils.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_AbsKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Activation.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_AdaptiveAveragePooling.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_AdaptiveAveragePooling3d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_AdaptiveMaxPooling2d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_AdaptiveMaxPooling3d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_AmpKernels.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_AveragePool2d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_AveragePool3d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_BatchLinearAlgebra.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_BatchLinearAlgebraLib.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_BinaryAddSubKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_BinaryBitwiseOpsKernels.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_BinaryLogicalOpsKernels.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_BinaryMiscBackwardOpsKernels.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_BinaryMiscOpsKernels.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_BinaryMulDivKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_BinaryRemainderKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_BinaryShiftOpsKernels.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Blas.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Bucketization.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Col2Im.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_CompareEQKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_CompareGEKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_CompareGTKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_CompareLEKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_CompareLTKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_CompareNEKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ComplexKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ConvolutionMM2d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Copy.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_CrossKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_DepthwiseConv2d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_DilatedMaxPool2d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_DilatedMaxPool3d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_DistanceKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_DistributionBernoulli.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_DistributionCauchyKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_DistributionExponentialKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_DistributionGeometricKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_DistributionLogNormalKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_DistributionNormal.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_DistributionRandomKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_DistributionUniform.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Distributions.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Dropout.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Embedding.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_EmbeddingBackwardKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_EmbeddingBag.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_FillKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ForeachBinaryOpList.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ForeachBinaryOpScalar.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ForeachBinaryOpScalarList.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ForeachPointwiseOp.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ForeachUnaryOp.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_FractionalMaxPool2d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_FractionalMaxPool3d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_FunctionOfAMatrixUtilsKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_GridSampler.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_HIPScalar.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Im2Col.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_IndexKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Indexing.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Lerp.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_LinearAlgebra.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Loss.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_LossCTC.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_MaxMinElementwiseKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_MaxUnpooling.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_MultinomialKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_NaiveConvolutionTranspose2d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_NaiveConvolutionTranspose3d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_NaiveDilatedConvolution.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Normalization.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_PointwiseOpsKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_PowKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_RNN.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_RangeFactories.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Reduce.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ReduceLogicKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ReduceMinMaxKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ReduceMomentKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ReduceNormKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ReduceSumProdKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ReflectionPad.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Repeat.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ReplicationPadding.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Resize.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ScanKernels.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_ScatterGatherKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Shape.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_SoftMax.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_SortingKthValue.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_SparseMM.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_SpectralOps.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_SummaryOps.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_TensorCompare.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_TensorFactories.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_TensorTransformations.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_TriangularOps.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UnaryComplexKernels.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UnaryFractionKernels.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UnaryGammaKernels.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UnaryGeometricKernels.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UnaryLogKernels.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UnaryOpsKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UnarySignKernels.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UnfoldBackwardKernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_Unique.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UpSampleBicubic2d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UpSampleBilinear2d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UpSampleLinear1d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UpSampleNearest1d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UpSampleNearest2d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UpSampleNearest3d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UpSampleTrilinear3d.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_WeightNorm.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_group_norm_kernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_layer_norm_kernel.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/sparse/hip/torch_hip_generated_SoftMax.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/sparse/hip/torch_hip_generated_SparseHIPBlas.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/sparse/hip/torch_hip_generated_SparseHIPTensor.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/sparse/hip/torch_hip_generated_SparseHIPTensorMath.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/quantized/hip/torch_hip_generated_affine_quantizer.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/quantized/hip/torch_hip_generated_fake_quantize_core.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/quantized/hip/torch_hip_generated_int_repr_quant.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/quantized/hip/torch_hip_generated_make_per_tensor_quantized_tensor.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHTensorMode.hip.o caffe2/CMakeFiles/torch_hip.dir/core/hip/torch_hip_generated_common_miopen.hip.o caffe2/CMakeFiles/torch_hip.dir/core/hip/torch_hip_generated_context_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/utils/math/hip/torch_hip_generated_broadcast.hip.o caffe2/CMakeFiles/torch_hip.dir/utils/math/hip/torch_hip_generated_elementwise.hip.o caffe2/CMakeFiles/torch_hip.dir/utils/math/hip/torch_hip_generated_reduce.hip.o caffe2/CMakeFiles/torch_hip.dir/utils/math/hip/torch_hip_generated_transpose.hip.o caffe2/CMakeFiles/torch_hip.dir/utils/hip/torch_hip_generated_math_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_abs_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_accumulate_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_accuracy_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_acos_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_affine_channel_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_alias_with_name.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_arg_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_asin_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_assert_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_atan_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_batch_gather_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_batch_matmul_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_batch_moments_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_batch_permutation_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_batch_sparse_to_dense_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_boolean_mask_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_boolean_unmask_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_bucketize_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_cast_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_cbrt_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_ceil_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_channel_backprop_stats_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_channel_shuffle_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_channel_stats_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_clip_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_conv_op_miopen.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_conv_transpose_op_miopen.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_copy_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_cos_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_cosh_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_cosine_embedding_criterion_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_cross_entropy_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_cube_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_data_couple_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_deform_conv_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_distance_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_dropout_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_elementwise_div_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_elementwise_linear_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_elementwise_mul_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_elementwise_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_elu_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_elu_op_miopen.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_enforce_finite_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_ensure_cpu_output_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_erf_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_filler_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_find_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_floor_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_gather_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_gelu_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_generate_proposals_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_generate_proposals_op_util_nms_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_given_tensor_byte_string_to_uint8_fill_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_given_tensor_fill_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_glu_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_group_norm_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_gru_unit_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_half_float_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_hard_sigmoid_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_instance_norm_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_integral_image_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_layer_norm_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_leaky_relu_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_lengths_pad_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_lengths_tile_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_local_response_normalization_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_local_response_normalization_op_miopen.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_logit_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_loss_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_lp_pool_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_lpnorm_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_lstm_unit_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_margin_ranking_criterion_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_max_pool_with_index.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_mean_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_mem_query_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_minmax_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_moments_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_multi_class_accuracy_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_normalize_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_one_hot_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_pack_segments.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_pad_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_perplexity_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_piecewise_linear_transform_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_pool_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_pool_op_miopen.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_pow_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_prelu_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_reciprocal_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_reduce_front_back_max_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_reduce_front_back_sum_mean_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_reduce_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_reduction_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_relu_n_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_relu_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_relu_op_miopen.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_replace_nan_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_resize_3d_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_resize_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_reverse_packed_segs_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_rmac_regions_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_rms_norm_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_roi_align_gradient_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_roi_align_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_roi_align_rotated_gradient_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_roi_align_rotated_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_roi_pool_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_rsqrt_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_scale_blobs_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_segment_reduction_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_selu_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_sequence_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_sigmoid_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_sigmoid_op_miopen.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_sin_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_sinh_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_slice_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_softmax_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_softplus_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_softsign_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_space_batch_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_sparse_lp_regularizer_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_sparse_normalize_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_sparse_to_dense_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_spatial_batch_norm_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_spatial_batch_norm_op_miopen.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_stump_func_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_summarize_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_swish_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_tan_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_tanh_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_tanh_op_miopen.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_thresholded_relu_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_tile_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_top_k.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_transpose_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_unique_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_upsample_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_utility_ops.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_weighted_sample_op.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/rnn/hip/torch_hip_generated_recurrent_network_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/operators/rnn/hip/torch_hip_generated_recurrent_op_miopen.hip.o caffe2/CMakeFiles/torch_hip.dir/sgd/hip/torch_hip_generated_adadelta_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/sgd/hip/torch_hip_generated_adagrad_fused_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/sgd/hip/torch_hip_generated_adagrad_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/sgd/hip/torch_hip_generated_adam_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/sgd/hip/torch_hip_generated_fp16_momentum_sgd_op.hip.o caffe2/CMakeFiles/torch_hip.dir/sgd/hip/torch_hip_generated_fp32_momentum_sgd_op.hip.o caffe2/CMakeFiles/torch_hip.dir/sgd/hip/torch_hip_generated_lars_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/sgd/hip/torch_hip_generated_momentum_sgd_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/sgd/hip/torch_hip_generated_rmsprop_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/sgd/hip/torch_hip_generated_yellowfin_op_gpu.hip.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/miopen/BatchNorm_miopen.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/miopen/Conv_miopen.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/miopen/RNN_miopen.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/cudnn/hip/AffineGridGenerator.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/cudnn/hip/BatchNorm.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/cudnn/hip/Conv.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/cudnn/hip/GridSampler.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/cudnn/hip/LossCTC.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/cudnn/hip/RNN.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/miopen/Descriptors.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/miopen/Handle.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/miopen/Types.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/sparse/hip/SparseHIPTensor.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/hip/CuSparseHandlePool.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/hip/CublasHandlePool.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/hip/CusolverDnHandlePool.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/hip/HIPBlas.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/hip/HIPContext.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/hip/HIPGeneratorImpl.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/hip/HIPSolver.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/hip/LegacyTHFunctionsHIP.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/hip/PinnedMemoryAllocator.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/hip/detail/HIPHooks.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/hip/impl/HIPCachingAllocatorMasqueradingAsCUDA.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/hip/impl/HIPGuardImplMasqueradingAsCUDA.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/HIPUnaryOps.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/LegacyDefinitions.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/TensorShapeHIP.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/CUDAType.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/QuantizedCUDAType.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/SparseCUDAType.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/THHCachingHostAllocator.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/THHGeneral.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/THHStorageCopy.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/THHTensor.cpp.o caffe2/CMakeFiles/torch_hip.dir/core/hip/blob_serialization_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/core/hip/common_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/core/hip/event_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/contrib/aten/hip/aten_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/contrib/nccl/hip/hip_nccl_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/contrib/nccl/hip/hip_nccl_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/contrib/gloo/hip/allreduce_ops_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/contrib/gloo/hip/broadcast_ops_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/contrib/gloo/hip/common_world_ops_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/db/hip/create_db_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/communicator_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/concat_split_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/conv_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/conv_op_shared_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/conv_transpose_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/counter_ops_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/do_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/elementwise_add_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/elementwise_sub_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/exp_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/expand_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/expand_squeeze_dims_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/free_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/fully_connected_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/if_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/im2col_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/load_save_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/locally_connected_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/log_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/matmul_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/negate_gradient_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/negative_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/order_switch_ops_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/prepend_dim_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/reshape_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/scale_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/shape_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/sqr_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/sqrt_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/stop_gradient_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/tensor_protos_db_input_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/while_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/hip/zero_gradient_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/rnn/hip/recurrent_network_blob_fetcher_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/operators/rnn/hip/recurrent_network_executor_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/queue/hip/queue_ops_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/sgd/hip/iter_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/sgd/hip/learning_rate_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/sgd/hip/weight_scale_op_gpu.cc.o caffe2/CMakeFiles/torch_hip.dir/__/torch/csrc/jit/codegen/fuser/cuda/fused_kernel.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/torch/csrc/autograd/profiler_cuda.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/torch/csrc/autograd/functions/comm.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/torch/csrc/cuda/comm.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/torch/csrc/jit/tensorexpr/cuda_codegen.cpp.o caffe2/CMakeFiles/torch_hip.dir/__/torch/csrc/cuda/nccl.cpp.o  -Wl,-rpath,/home/isaac/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/lib:/opt/rocm/hip/lib:/opt/rocm/miopen/lib:/opt/rocm/rccl/lib:/opt/rocm/roctracer/lib:/opt/rocm/rocblas/lib:/opt/rocm/rocfft/lib:/opt/rocm/hiprand/lib:/opt/rocm/hipsparse/lib:/opt/intel/mkl/lib/intel64:/opt/rocm/lib:/opt/rocm/rocrand/lib:/usr/lib/openmpi:  lib/libc10_hip.so  /opt/rocm/hip/lib/libamdhip64.so  /opt/rocm/miopen/lib/libMIOpen.so  /opt/rocm/rccl/lib/librccl.so  /opt/rocm/hip/lib/libamdhip64.so  /opt/rocm/roctracer/lib/libroctx64.so  /opt/rocm/rocblas/lib/librocblas.so.0.1  /opt/rocm/rocfft/lib/librocfft.so.0.1  /opt/rocm/hiprand/lib/libhiprand.so.1.1  /opt/rocm/hipsparse/lib/libhipsparse.so.0.1  lib/libgloo_hip.a  lib/libc10.so  -Wl,--no-as-needed,"/home/isaac/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/lib/libtorch_cpu.so" -Wl,--as-needed  lib/libprotobuf.a  /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so  /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so  /opt/intel/mkl/lib/intel64/libmkl_core.so  -fopenmp  /usr/lib/libpthread.so  -lm  /usr/lib/libdl.so  lib/libdnnl.a  -pthread  -ldl  /opt/rocm/hip/lib/libamdhip64.so.4.0.20514-  -L/opt/rocm/llvm/lib/clang/12.0.0/include/../lib/linux  -lclang_rt.builtins-x86_64  /opt/rocm/hip/lib/libamdhip64.so  lib/libgloo.a  /usr/lib/openmpi/libmpi_cxx.so  /usr/lib/openmpi/libmpi.so  -lpthread  -Wl,-rpath-link,/opt/rocm/lib:/opt/rocm/rocfft/lib:/opt/rocm/rocrand/lib && :
c++: error: -E or -x required when input is from standard input
```

**Comment by acxz** [comment]
reopening as it seems that some people are still facing this issue.

**Comment by acxz** [comment]
@erratic-c-programmer

Are you using the `arch4edu` repos? Can you try to build the rocm packages yourself and try compiling this package again?

Also just to make sure, can you list which version of the package you are trying to build? Let's make sure it is the latest one.

**Comment by erratic-c-programmer** [comment]
When I tried building all from source, one of the deps failed

**Comment by erratic-c-programmer** [comment]
I can't remember which, but I think it had something to do with precompiled kernels

**Comment by acxz** [comment]
If you could post the error that would be great. As for now, I had thought that we had gotten rid of this error. I would make sure you are using the latest versions of all the packages.

**Comment by JP-Ellis** [comment]
I have been having the same issue and it is because the `hip-rocclr` package creates the following files:

```
❯ ls -lah /opt/rocm/hip/lib/*.so*
Name
/opt/rocm/hip/lib/libamdhip64.so -> libamdhip64.so.4
/opt/rocm/hip/lib/libamdhip64.so.4 -> libamdhip64.so.4.0.20515-
/opt/rocm/hip/lib/libamdhip64.so.4.0.20515-
```

The CMake/ninja build finds the last file, which for some reason ends with a `-` which causes an error during linking as it interprets this to be the standard input.

Replacing every instance of `/opt/rocm/hip/lib/libamdhip64.so.4.0.20515-` with one of the other two in the ninja build fixes the issue.  This might actually be an issue with the `hip-rocclr` package then as it seems like files ending with a dash are not expected.

A temporary fix for this is to replace the path to this library in `build.ninja`.  The following works for me:

```patch
- python setup.py build
+ python setup.py build --cmake-only
+ sed -i 's/\/opt\/rocm\/hip\/lib\/libamdhip64.so.4.0.20515-/\/opt\/rocm\/hip\/lib\/libamdhip64.so.4/' build/build.ninja
+ python setup.py install
```

I don't know if there's a way to tell CMake to use a specific shared library when there are multiple available, but that would be preferred (if these arguments can be passed to cmake within the python setup script).

**Comment by acxz** [comment]
o.O nice find!

Do you want to make a PR for this for a temporary patch, until we find something more permanent?

**Comment by JP-Ellis** [comment]
I can make a patch, but I would prefer if there's a better way of specifying which `.so` file is used.  I'll have a look today and create a pull request.

**Comment by acxz** [comment]
Looks like this issue is resolved and ninja can find the amdhip library without the sed parsing. I'm closing this issue for now and if people still experience it then please feel free to comment and I'll reopen it.

**Comment by acxz** [comment]
This might actually still be a problem (or something similar based on the above mentioned issue). Keeping this open for now actually.

Maybe I didn't run into this problem just now since I built `hip-runtime-amd` with `git` installed?
In that case it shouldn't be too difficult to modify the `sed` command to work for both cases. (`so.XXX-YYY` and `so.XXX-`)

**Comment by acxz** [comment]
related issue: https://github.com/rocm-arch/rocm-arch/issues/684

**Comment by JP-Ellis** [comment]
Thanks for fixing the underlying cause of the issue :+1: 

Since `hip-runtime-amd` should no longer be installing this problematic files (at least not since 5.0.1), should we mark this as closed?

**Comment by acxz** [comment]
I wanted one other person to confirm and install `pytorch-rocm` successfully first. But yeah let's close it and if it comes up again we'll take a look at this again.

**Comment by JP-Ellis** [comment]
I have successfully built `pytorch-rocm` today.  All that was missing at the time was `rocm_agent_enumerator` which wasn't provided by `rocminfo`.  I have a separate pull request to address this at rocm-arch/rocm-arch#707
